#pragma once
#include "WhileNode.h"
#include "ForNode.h"
#include "BinOpNode.h"
#include "UnaryOpNode.h"
#include "NumberNode.h"
#include "IfNode.h"
#include "VarAccessNode.h"
#include "VarAssignNode.h"